### ISSUE TITLE
Update $story to be server specific

### ISSUE THREAD

**Issue by The1CABAL** [The1CABAL/SkaldBot#12]
In order for the Skald to be smoothly imported to multiple servers we need to capture the server ID on message receive (discord.py already does this) and return a response based on what server the message came from.

**Comment by The1CABAL** [comment]
Wouldn't it be simpler to store the server IDs in a list format inserted into a column in the stories table?

That way, when running the $story command we can capture the server id from the message context and when the query is run it would be something like `"select * from Stories where DiscordServerId like %?%", id`

**Comment by DevinWalkup** [comment]
After discussion we are continuing with the lookup table idea.

**Comment by The1CABAL** [comment]
Moving back to backlog until I can create seed and update the command functions
