### ISSUE TITLE
UI - Submit Idea

### ISSUE THREAD

**Issue by DevinWalkup** [The1CABAL/SkaldBot#70]
Currently, the Submit Idea page is a public accessible feature. With the addition of the server id column in the stories and wisdom table, we will need to decide if this should remain a public feature. 

The easy fix for this would to require a user to be logged in to submit an idea. This could also limit the risk of the database being flooded with an abundance of suggestions and will allow for a select list of servers linked to the account.

If we decide to keep this a public accessible feature, we need to decide how we want to handle these submitted ideas. Do we default these to the main server id in the database? If so, we may need to add a new column to the servers table called IsDefault. Or do we have them input the server id manually?

**Comment by The1CABAL** [comment]
Maybe instead of having to make so many accounts we can let this be a user under the discord server owners account, and the owner could designate approvers? 

The goal here should be the least complicated solution. As it stands I do not expect many users other than discord server owners

**Comment by DevinWalkup** [comment]
@The1CABAL I can add a new role for approving, but are we keeping this a public feature or a feature that requires the user to be logged in. And this wouldn't increase the total number of accounts. There can be multiple users per account though. 

I just need to know how we plan on handling the server id requirement.

**Comment by The1CABAL** [comment]
Keep it public

**Comment by The1CABAL** [comment]
> I just need to know how we plan on handling the server id requirement. 

Keep it public
